# Dicionário dos dados

### `SeriousDlqin2yrs`
Person experienced 90 days past due delinquency or worse. | Y/N

O cliente teve inadimplência de 90 ou mais dias nos últimos 2 anos?

### `RevolvingUtilizationOfUnsecuredLine` 
Total balance on credit cards and personal lines of credit except real estate and no installment debt like car loans divided by the sum of credit limits. | percentage

Saldo total em cartões de crédito e linhas de crédito pessoais, excluindo imóveis e dívidas não parceladas, como financiamentos de automóveis, dividido pela soma dos limites de crédito.

Quanto da linha de crédito rotativo o cliente está usando? (0 = nada, 1 = 100%)

### `age`
Age of borrower in years. | integer

Idade do cliente.

### `NumberOfTime30-59DaysPastDueNotWorse`
Number of times borrower has been 30-59 days past due but no worse in the last 2 years. | integer

Quantas vezes o cliente atrasou entre 30 e 59 dias nos últimos 2 anos.

### `DebtRatio`
Monthly debt payments, alimony,living costs divided by monthly gross income. | percentage

Pagamentos mensais de dívidas (dívidas, pensão alimentícia e despesas de subsistência) divididos pela renda bruta mensal.

### `MonthlyIncome`
Monthly income. | real

Renda mensal em dólares.

### `NumberOfOpenCreditLinesAndLoans`
Number of Open loans (installment like car loan or mortgage) and Lines of credit (e.g. credit cards). | integer

Número de linhas de crédito e empréstimos abertos.

### `NumberOfTimes90DaysLate`
Number of times borrower has been 90 days or more past due. | integer

Quantas vezes o cliente ficou 90+ dias em atraso.

### `NumberRealEstateLoansOrLine`
Number of mortgage and real estate loans including home equity lines of credit. | integer

Número de empréstimos hipotecários e imobiliários, incluindo linhas de crédito com garantia imobiliária.

### `NumberOfTime60-89DaysPastDueNotWorse`
Number of times borrower has been 60-89 days past due but no worse in the last 2 years. | integer

Quantas vezes o cliente atrasou entre 60 e 89 dias.

### `NumberOfDependents`
Number of dependents in family excluding themselves (spouse, children etc.). | integer

Número de dependentes (cônjuge, filhos, etc.).

# 01. Carregando e Visão Geral do Dados

In [ ]:
import pandas as pd
import seaborn as sns
import streamlit as st

pd.set_option('display.max_columns', None)

In [17]:
df = pd.read_csv('../data/cs-training.csv',index_col=0)

In [18]:
df.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [19]:
df.shape

(150000, 11)

In [20]:
df.head(5)

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 1 to 150000
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   SeriousDlqin2yrs                      150000 non-null  int64
 1   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 2   age                                   150000 non-null  int64
 3   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  int64
 4   DebtRatio                             150000 non-null  float64
 5   MonthlyIncome                         120269 non-null  float64
 6   NumberOfOpenCreditLinesAndLoans       150000 non-null  int64
 7   NumberOfTimes90DaysLate               150000 non-null  int64
 8   NumberRealEstateLoansOrLines          150000 non-null  int64
 9   NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  int64
 10  NumberOfDependents                    146076 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 12.6 MB

In [22]:
## verificar os dados de cada coluna numérica
df.describe()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,1.202690e+05,150000.000000,150000.000000,150000.000000,150000.000000,146076.000000
mean,0.066840,6.048438,52.295207,0.421033,353.005076,6.670221e+03,8.452760,0.265973,1.018240,0.240387,0.757222
std,0.249746,249.755371,14.771866,4.192781,2037.818523,1.438467e+04,5.145951,4.169304,1.129771,4.155179,1.115086
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.029867,41.000000,0.000000,0.175074,3.400000e+03,5.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.154181,52.000000,0.000000,0.366508,5.400000e+03,8.000000,0.000000,1.000000,0.000000,0.000000
75%,0.000000,0.559046,63.000000,0.000000,0.868254,8.249000e+03,11.000000,0.000000,2.000000,0.000000,1.000000
max,1.000000,50708.000000,109.000000,98.000000,329664.000000,3.008750e+06,58.000000,98.000000,54.000000,98.000000,20.000000

In [23]:
## qtd de valores nulos
print('Quantidade de valores nulos:')
nulls = df.isnull().sum()
print(nulls[nulls>0])

Quantidade de valores nulos:
MonthlyIncome         29731
NumberOfDependents     3924
dtype: int64

In [24]:
## % de valores nulos
print('% de valores nulos:')
nulls_percentage = (df.isnull().sum()/len(df)*100)
print(nulls_percentage[nulls_percentage>0])

% de valores nulos:
MonthlyIncome         19.820667
NumberOfDependents     2.616000
dtype: float64

In [25]:
## quantidade de valores únicos em cada coluna
df.nunique().sort_values(ascending=True)

SeriousDlqin2yrs                             2
NumberOfTime60-89DaysPastDueNotWorse        13
NumberOfDependents                          13
NumberOfTime30-59DaysPastDueNotWorse        16
NumberOfTimes90DaysLate                     19
NumberRealEstateLoansOrLines                28
NumberOfOpenCreditLinesAndLoans             58
age                                         86
MonthlyIncome                            13594
DebtRatio                               114194
RevolvingUtilizationOfUnsecuredLines    125728
dtype: int64

In [26]:
df[df['age']>100]

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
7764,0,0.069167,101,0,50.000000,NaN,2,0,0,0,0.0
19885,0,1.000000,103,0,0.000000,1600.0,3,0,0,0,0.0
25562,0,0.009866,102,0,0.002424,3300.0,3,0,0,0,0.0
40008,0,0.064748,107,0,939.000000,NaN,9,0,1,0,0.0
56762,0,0.003469,105,0,2.000000,NaN,4,0,0,0,NaN
57968,0,0.001397,103,0,1798.500000,1.0,11,0,2,0,0.0
90938,0,0.000000,102,0,0.000000,NaN,12,0,0,0,0.0
93814,0,0.025780,101,0,0.013797,1666.0,5,0,0,0,0.0
96451,0,0.109642,102,0,0.273844,3417.0,7,0,0,0,1.0
105791,0,0.109307,109,0,2141.000000,NaN,17,0,1,0,NaN
116130,1,0.002964,101,2,0.001387,2883.0,6,0,0,0,0.0
135026,0,0.004059,103,0,5.000000,NaN,6,0,0,0,0.0
138292,0,0.246529,109,0,318.000000,NaN,3,0,0,0,NaN

In [27]:
df.duplicated().sum()

np.int64(609)

In [28]:
df['SeriousDlqin2yrs'].value_counts()

SeriousDlqin2yrs
0    139974
1     10026
Name: count, dtype: int64

In [29]:
df['SeriousDlqin2yrs'].value_counts(normalize=True)

SeriousDlqin2yrs
0    0.93316
1    0.06684
Name: proportion, dtype: float64

# 02. Limpeza dos Dados

# 03. Análise Exploratória

# 04. Visualização

# 05. Conclusão